server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./data/lyricdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: warn
    org.hibernate.type.descriptor.sql.BasicBinder: warn

app:
  ai:
    base-url: http://127.0.0.1:8001


  cors:
    allowed-origins: "http://localhost:3000"
  openai:
    api-key: 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
    model: gpt-4o-mini
    enabled: true